Migrate gotest extension from azure-tools to this repo
Azure/autorest.go pull request #845
Opened 2022-07-04 06:03 UTC by tadelesh

This PR try to migrate all the code of @autorest/gotest extension. Original code position: https://github.com/Azure/azure-sdk-tools/tree/main/tools/sdk-testgen/packages/autorest.gotest. Reuse `rush` to manage mono package. Two extensions will get separate eng script and build/release process for @autorest/go remains unchanged.

2022-07-05 02:19 UTC, lirenhe commented
@tadelesh,  there are CI failure for this PR, could you check the root cause?

2022-07-05 02:20 UTC, tadelesh commented
> @tadelesh, there are CI failure for this PR, could you check the root cause?

I'm working on the CI issue.

2022-07-05 15:23 UTC, jhendrixMSFT requested changes
Can you please update `CODEOWNERS` as required?

2022-07-07 14:46 UTC, jhendrixMSFT approved these changes

2022-07-08 03:34 UTC, merged